### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by leonitousconforti** [Unabatedlynx5/7038-romi#1]
When I try to build the romi project, it fails with the message:

* What went wrong:
Execution failed for task ':extractTestJNI'.
> Could not resolve all files for configuration ':nativeDesktopZip'.
   > Could not find opencv-cpp-3.4.7-5-osxx86.zip (edu.wpi.first.thirdparty.frc2021.opencv:opencv-cpp:3.4.7-5).
     Searched in the following locations:
         https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/thirdparty/frc2021/opencv/opencv-cpp/3.4.7-5/opencv-cpp-3.4.7-5-osxx86.zip

Did you have to change any special configuration settings before building?

**Comment by Unabatedlynx5** [comment]
No

**Comment by leonitousconforti** [comment]
Does it build on your laptop?

**Comment by Unabatedlynx5** [comment]
yes

**Comment by leonitousconforti** [comment]
got it working, I had to use wpilib's specific java jdk and install the libraries
